#!/usr/bin/env bash
# Render ~/.needle/config.yaml for a single-worker pod.
#
# Every value here is a pod-specific departure from the bare-metal defaults;
# where the reason is not obvious it is stated inline, because the next person
# to read this will be triaging a worker that behaved unexpectedly.

# shellcheck source=common.sh
. "${NEEDLE_POD_LIB}/common.sh"

render_needle_config() {
    # ~/.config/needle/config.yaml is the global config NEEDLE actually loads
    # (ConfigLoader, src/config/mod.rs:2095). NOT ~/.needle/config.yaml — that
    # path exists on the bare-metal box as a stale leftover and is read by
    # nothing, so writing there renders a perfectly valid config that the
    # worker silently ignores while falling back to every default.
    local config="${NEEDLE_CONFIG_FILE:-$HOME/.config/needle/config.yaml}"
    local workspaces_dir="${NEEDLE_POD_WORKSPACES_DIR:-$HOME/workspaces}"
    local default_agent="${NEEDLE_POD_DEFAULT_AGENT:?default agent not resolved}"

    # One worker per pod. This is the whole point of the deployment shape —
    # scaling is replicas, not in-pod workers.
    local max_workers=1

    # idle_action=wait, not exit. Bare-metal workers exit on an empty ready
    # pool, which inside a Deployment is indistinguishable from
    # CrashLoopBackOff. Wait is NEEDLE's default as of the IdleAction work, but
    # it is set explicitly so a future default flip cannot silently break pods.
    local idle_action="${NEEDLE_POD_IDLE_ACTION:-wait}"

    # Day-granular retention on the JSONL sink. This IS enforced — the mend
    # strand reads telemetry.file_sink.retention_days (src/strand/mod.rs) and
    # prunes agent log files. It is the config key that works; mend.max_log_files
    # is declared in config but appears nowhere in the source and prunes nothing.
    # A size-bounded sweep in telemetry.sh backstops this, because day
    # granularity is too coarse for a bounded emptyDir.
    local log_retention_days="${NEEDLE_POD_LOG_RETENTION_DAYS:-3}"

    # OTLP remains opt-in so an image can run before its cluster-local gateway
    # exists. When enabled, pods send to that gateway; the gateway owns the
    # cross-cluster credential and adds the trusted deployment identity.
    local otlp_enabled="${NEEDLE_POD_OTLP_ENABLED:-false}"
    local otlp_endpoint="${NEEDLE_POD_OTLP_ENDPOINT:-http://needle-otel-gateway:4318}"
    local otlp_protocol="${NEEDLE_POD_OTLP_PROTOCOL:-http}"
    local otlp_compression="${NEEDLE_POD_OTLP_COMPRESSION:-gzip}"
    local otlp_auth_env="${NEEDLE_POD_OTLP_AUTH_ENV:-}"
    local deployment_cluster="${NEEDLE_POD_DEPLOYMENT_CLUSTER:-agent-sandbox}"
    local worker_pool="${NEEDLE_POD_WORKER_POOL:-default}"

    # stdout_sink stays off deliberately. It is implemented, but emits
    # human-readable text (Minimal/Normal/Verbose) rather than JSON, so it is
    # not a substitute for shipping the JSONL — enabling both would duplicate
    # every event in `kubectl logs`. See docs/notes/worker-image.md.
    local stdout_enabled="${NEEDLE_POD_STDOUT_SINK_ENABLED:-false}"

    # How long before mend considers a claim stuck and reclaims it.
    #
    # NOT `heartbeat_max_age`. That key appears in the bare-metal config.yaml
    # and in this project's earlier notes, but it exists nowhere in NEEDLE's
    # source — it is inert, exactly like mend.max_log_files. Setting it looked
    # like a preemption mitigation while doing nothing at all. stuck_threshold_secs
    # is the real control (src/config/mod.rs, MendConfig).
    local stuck_threshold="${NEEDLE_POD_STUCK_THRESHOLD_SECS:-900}"

    mkdir -p "$(dirname "$config")"

    {
        echo "# Generated by needle-pod at container start. Do not edit in-pod —"
        echo "# it is overwritten on every restart. Change the ConfigMap instead."
        echo
        echo "needle:"
        echo "  version: 1"
        echo
        echo "workspace:"
        echo "  default: ${workspaces_dir}"
        echo "  home: ${workspaces_dir}"
        echo
        echo "worker:"
        echo "  max_workers: ${max_workers}"
        # NOTE: `worker.default_agent` is NOT a config field. It appears in the
        # bare-metal config.yaml but no such key exists on WorkerConfig — the
        # adapter is chosen by `agent.default` below. Setting it here would be
        # inert, and the worker would fall back to the built-in default
        # ("claude"), claim a bead, then die at dispatch with "configured agent
        # adapter 'claude' not found" — leaving the bead claimed.
        echo "  idle_action: ${idle_action}"
        echo "  idle_backoff_min: ${NEEDLE_POD_IDLE_BACKOFF_MIN:-30}"
        echo "  idle_backoff_max: ${NEEDLE_POD_IDLE_BACKOFF_MAX:-300}"
        echo
        # explore and mend are nested under `strands:` — NOT top level. A
        # top-level `explore:` block is silently ignored by serde, which leaves
        # workspace_root defaulting to $HOME; discovery then reports count=0
        # and the worker idles with a fully hydrated repo one directory away.
        echo "strands:"
        echo "  explore:"
        echo "    enabled: true"
        echo "    workspace_root: ${workspaces_dir}"

        # Empty `workspaces` means recursive auto-discovery under
        # workspace_root — the fleet default, and what preserves roaming.
        # A non-empty list PINS the worker and makes it blind to new repos;
        # NEEDLE logs a WARN when it is set, which is the intended signal.
        local pinned
        pinned="$(split_list "${NEEDLE_POD_PINNED_WORKSPACES:-}")"
        if [ -n "$pinned" ]; then
            log_warn "worker is pinned to an explicit workspace list; roaming disabled" \
                --arg workspaces "$(echo "$pinned" | tr '\n' ' ')"
            echo "    workspaces:"
            while IFS= read -r w; do
                [ -n "$w" ] && echo "      - ${workspaces_dir}/${w}"
            done <<< "$pinned"
        else
            echo "    workspaces: []"
        fi

        echo
        echo "telemetry:"
        echo "  file_sink:"
        echo "    enabled: true"
        echo "    log_dir: ${NEEDLE_HOME}/logs"
        echo "    retention_days: ${log_retention_days}"
        echo "  stdout_sink:"
        echo "    enabled: ${stdout_enabled}"
        echo "    format: minimal"
        echo "    color: never"
        echo "  otlp_sink:"
        echo "    enabled: ${otlp_enabled}"
        echo "    endpoint: \"${otlp_endpoint}\""
        echo "    protocol: \"${otlp_protocol}\""
        echo "    compression: \"${otlp_compression}\""
        echo "    resource_attributes:"
        echo "      - \"deployment.cluster=${deployment_cluster}\""
        echo "      - \"needle.worker.pool=${worker_pool}\""
        if [ -n "$otlp_auth_env" ]; then
            echo "    headers:"
            echo "      - \"Authorization: env:${otlp_auth_env}\""
        else
            echo "    headers: []"
        fi
        # Also under strands:. A preempted pod cannot drain its in-flight
        # dispatch (the supervisor breaks its loop without awaiting children),
        # so the bead stays claimed until mend reclaims it. Shortening that
        # window is the only mitigation available from config alone; the real
        # fix is an upstream drain.
        echo "  mend:"
        echo "    stuck_threshold_secs: ${stuck_threshold}"
        echo
        echo "agent:"
        # THE key that selects the adapter. Must name a YAML file that
        # render.py actually wrote into adapters_dir.
        echo "  default: ${default_agent}"
        echo "  adapters_dir: ${NEEDLE_ADAPTERS_DIR:-$HOME/.config/needle/adapters}"
        echo "  timeout: ${NEEDLE_POD_AGENT_TIMEOUT:-3600}"
        echo "  routing:"
        echo "    rules:"
        echo "      - match_model: \".*\""
        echo "        adapter: ${default_agent}"
    } > "$config"

    log_info "rendered needle config" \
        --arg path "$config" \
        --arg default_agent "$default_agent" \
        --arg idle_action "$idle_action" \
        --arg workspace_root "$workspaces_dir" \
        --arg retention_days "$log_retention_days" \
        --arg otlp_enabled "$otlp_enabled" \
        --arg otlp_endpoint "$otlp_endpoint" \
        --arg deployment_cluster "$deployment_cluster" \
        --arg worker_pool "$worker_pool"
}
