#!/usr/bin/env bash
# Render ~/.needle/config.yaml for a single-worker pod.
#
# Every value here is a pod-specific departure from the bare-metal defaults;
# where the reason is not obvious it is stated inline, because the next person
# to read this will be triaging a worker that behaved unexpectedly.

# shellcheck source=common.sh
. "${NEEDLE_POD_LIB}/common.sh"

render_needle_config() {
    local config="${NEEDLE_HOME}/config.yaml"
    local workspaces_dir="${NEEDLE_POD_WORKSPACES_DIR:-$HOME/workspaces}"
    local default_agent="${NEEDLE_POD_DEFAULT_AGENT:?default agent not resolved}"

    # One worker per pod. This is the whole point of the deployment shape —
    # scaling is replicas, not in-pod workers.
    local max_workers=1

    # idle_action=wait, not exit. Bare-metal workers exit on an empty ready
    # pool, which inside a Deployment is indistinguishable from
    # CrashLoopBackOff. Wait is NEEDLE's default as of the IdleAction work, but
    # it is set explicitly so a future default flip cannot silently break pods.
    local idle_action="${NEEDLE_POD_IDLE_ACTION:-wait}"

    # Day-granular retention on the JSONL sink. This IS enforced — the mend
    # strand reads telemetry.file_sink.retention_days (src/strand/mod.rs) and
    # prunes agent log files. It is the config key that works; mend.max_log_files
    # is declared in config but appears nowhere in the source and prunes nothing.
    # A size-bounded sweep in telemetry.sh backstops this, because day
    # granularity is too coarse for a bounded emptyDir.
    local log_retention_days="${NEEDLE_POD_LOG_RETENTION_DAYS:-3}"

    # OTLP off: there is no collector inside the pod, and localhost:4318 would
    # just generate connection errors. JSONL events carry the failure signal.
    local otlp_enabled="${NEEDLE_POD_OTLP_ENABLED:-false}"

    # stdout_sink stays off deliberately. It is implemented, but emits
    # human-readable text (Minimal/Normal/Verbose) rather than JSON, so it is
    # not a substitute for shipping the JSONL — enabling both would duplicate
    # every event in `kubectl logs`. See docs/notes/worker-image.md.
    local stdout_enabled="${NEEDLE_POD_STDOUT_SINK_ENABLED:-false}"

    local heartbeat_max_age="${NEEDLE_POD_HEARTBEAT_MAX_AGE:-900}"

    mkdir -p "$(dirname "$config")"

    {
        echo "# Generated by needle-pod at container start. Do not edit in-pod —"
        echo "# it is overwritten on every restart. Change the ConfigMap instead."
        echo
        echo "needle:"
        echo "  version: 1"
        echo
        echo "workspace:"
        echo "  default: ${workspaces_dir}"
        echo "  home: ${workspaces_dir}"
        echo
        echo "worker:"
        echo "  max_workers: ${max_workers}"
        echo "  default_agent: ${default_agent}"
        echo "  idle_action: ${idle_action}"
        echo "  idle_backoff_min: ${NEEDLE_POD_IDLE_BACKOFF_MIN:-30}"
        echo "  idle_backoff_max: ${NEEDLE_POD_IDLE_BACKOFF_MAX:-300}"
        echo
        echo "explore:"
        echo "  enabled: true"
        echo "  workspace_root: ${workspaces_dir}"

        # Empty `workspaces` means recursive auto-discovery under
        # workspace_root — the fleet default, and what preserves roaming.
        # A non-empty list PINS the worker and makes it blind to new repos;
        # NEEDLE logs a WARN when it is set, which is the intended signal.
        local pinned
        pinned="$(split_list "${NEEDLE_POD_PINNED_WORKSPACES:-}")"
        if [ -n "$pinned" ]; then
            log_warn "worker is pinned to an explicit workspace list; roaming disabled" \
                --arg workspaces "$(echo "$pinned" | tr '\n' ' ')"
            echo "  workspaces:"
            while IFS= read -r w; do
                [ -n "$w" ] && echo "    - ${workspaces_dir}/${w}"
            done <<< "$pinned"
        else
            echo "  workspaces: []"
        fi

        echo
        echo "telemetry:"
        echo "  file_sink:"
        echo "    enabled: true"
        echo "    log_dir: ${NEEDLE_HOME}/logs"
        echo "    retention_days: ${log_retention_days}"
        echo "  stdout_sink:"
        echo "    enabled: ${stdout_enabled}"
        echo "    format: minimal"
        echo "    color: never"
        echo "  otlp_sink:"
        echo "    enabled: ${otlp_enabled}"
        echo
        echo "mend:"
        # Lower than the bare-metal 3600. A preempted pod cannot drain its
        # in-flight dispatch (the supervisor breaks its loop without awaiting
        # children), so the bead stays claimed until the stale reaper releases
        # it. Shorter heartbeat_max_age is the mitigation available from
        # config alone; the real fix is an upstream drain.
        echo "  heartbeat_max_age: ${heartbeat_max_age}"
        echo
        echo "agent:"
        echo "  routing:"
        echo "    rules:"
        echo "      - match_model: \".*\""
        echo "        adapter: ${default_agent}"
    } > "$config"

    log_info "rendered needle config" \
        --arg path "$config" \
        --arg default_agent "$default_agent" \
        --arg idle_action "$idle_action" \
        --arg retention_days "$log_retention_days"
}
